### ISSUE TITLE
Issues on new raspbian Linux version 5.10.17

### ISSUE THREAD

**Issue by NimrodelGR** [mikenye/gitbook-adsb-guide#30]
Hello,

followed the guide some months ago on a RPi 3b+ with earlier version of raspbian with no problems.

Trying in a new installation and I get the following error:

readsb        | [collectd] 2021/08/20 00:06:36 [2021-08-20 00:06:37] plugin_load: plugin "logfile" successfully loaded.
readsb        | [collectd] 2021/08/20 00:06:36 [error] nanosleep failed: Operation not permitted
readsb        | sleep: cannot read realtime clock: Operation not permitted
readsb        | sleep: cannot read realtime clock: Operation not permitted
readsb        | sleep: cannot read realtime clock: Operation not permitted

the same for tar1090

**Comment by mikenye** [comment]
Hi @NimrodelGR, this is an issue with docker. I would suggest attempting to upgrade docker.

A workaround is to set `privileged: true` on the affected containers.

**Comment by NimrodelGR** [comment]
Hi again @mikenye and thank you for your efforts.

I've already formatted and tried from scratch. Will post it when I'm able to replicate the issue.

Currently I cannot get past installing docker.

The script returns: E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by NimrodelGR** [comment]
Hello again,

revisited the guide and everything is going smoothly now.

Thanks once again!

**Comment by mikenye** [comment]
I'm glad everything is working for you!
