### ISSUE TITLE
Issues (n.2) on new raspbian Linux version 5.10.17

### ISSUE THREAD

**Issue by NimrodelGR** [mikenye/gitbook-adsb-guide#31]
Hello,

followed the guide some months ago on a RPi 3b+ with earlier version of raspbian with no problems.

Trying in a new installation and I got the following error when I tried to run "docker-compose version":

docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create": dial unix /var/run/docker.sock: connect: permission denied.

Fixed with:

sudo groupadd docker
sudo usermod -aG docker ${USER}

from:
https://www.digitalocean.com/community/questions/how-to-fix-docker-got-permission-denied-while-trying-to-connect-to-the-docker-daemon-socket

Wandering if it was the correct way.

**Comment by mikenye** [comment]
Yes, that's correct. You could also prefix your `docker-compose` commands with `sudo`.
